language: python
cache: pip
sudo: false

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=3.0
  - DJANGO=4.0

install:
  - pip install jinja2 mako tornado six coverage nose codecov flake8 charset_normalizer
  - pip install django==$DJANGO

matrix:
  fast_finish: true
  exclude:
    - { python: "3.4", env: DJANGO=3.0 }
    - { python: "3.5", env: DJANGO=3.0 }

#    allow_failures:
#      - env: DJANGO=master

script:
  - make coverage

after_success:
  - codecov
